CREATE TABLE [dbo].[TagQrCode] ( 
	[IdTag] CHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[NomeTag] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[TamanhoTag] CHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[TipoTag] CHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[DescricaoTag] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[TagValue] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,CONSTRAINT [PK_TagQrCode] PRIMARY KEY CLUSTERED (IdTag ASC) WITH FILLFACTOR = 90
	);
