CREATE TABLE [dbo].[ControleTransacoes] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[CodigoReferencia] INT NULL
	,[DataHora] DATETIME NULL
	,[TipoMensagem] CHAR(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Terminal] CHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Estabelecimento] VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Rede] INT NULL
	,[NsuMeioCaptura] CHAR(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[NsuTrnOriginal] CHAR(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Valor] VARCHAR(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[HoraTerminal] CHAR(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[DataTerminal] CHAR(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[CodigoResposta] INT NULL
	,CONSTRAINT [PK_ControleTransacoes] PRIMARY KEY CLUSTERED (Codigo DESC) WITH FILLFACTOR = 80
	);

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_Codigo_CodigoReferencia] ON [dbo].[ControleTransacoes] (Codigo ASC, CodigoReferencia ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_TipoMensagem] ON [dbo].[ControleTransacoes] (TipoMensagem ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_Estabelecimento] ON [dbo].[ControleTransacoes] (Estabelecimento ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_Rede] ON [dbo].[ControleTransacoes] (Rede ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_NsuMeioCaptura] ON [dbo].[ControleTransacoes] (NsuMeioCaptura ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_NsuTrnOriginal] ON [dbo].[ControleTransacoes] (NsuTrnOriginal ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_Valor] ON [dbo].[ControleTransacoes] (Valor ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ControleTransacoes_DataHora] ON [dbo].[ControleTransacoes] (DataHora ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 80, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

