CREATE TABLE [dbo].[Aut_Chaves_SE_TMK] ( 
	[IdChave] INT IDENTITY(1,1) NOT NULL
	,[LenChave] CHAR(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[LabelChave] VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[ValueChave] VARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[KCVChave] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[Data] DATETIME NULL
	,CONSTRAINT [PK_Aut_Chaves_SE_TMK] PRIMARY KEY CLUSTERED (IdChave ASC) WITH FILLFACTOR = 80
	);
