CREATE TABLE [dbo].[DebugAdilson] ( 
	[Id] BIGINT IDENTITY(1,1) NOT NULL
	,[DebugMessage] VARCHAR(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[DebugDate] DATETIME NOT NULL CONSTRAINT [DF__DebugAdil__Debug__42B7D1CC] DEFAULT (getdate())
	,CONSTRAINT [PK__DebugAdi__3214EC07941C12C4] PRIMARY KEY CLUSTERED (Id ASC) WITH FILLFACTOR = 90
	);
