CREATE TABLE [dbo].[WorkingKey] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[Terminal] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[ChaveTrabalho] VARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[DataCriacaoChave] DATETIME NULL
	,[Provedor] VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Estabelecimento] VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,CONSTRAINT [PK_WorkingKey] PRIMARY KEY CLUSTERED (Codigo DESC) WITH FILLFACTOR = 90
	);

CREATE NONCLUSTERED INDEX [IX_WorkingKey_Terminal] ON [dbo].[WorkingKey] (Terminal ASC)
	INCLUDE (Estabelecimento)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_WorkingKey05] ON [dbo].[WorkingKey] (Provedor ASC, Estabelecimento ASC)
	INCLUDE (Codigo, ChaveTrabalho)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_WorkingKey_Terminal_ChaveTrabalho_DataCriacaoChave] ON [dbo].[WorkingKey] (Terminal ASC)
	INCLUDE (ChaveTrabalho, DataCriacaoChave)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IDX_N_WorkingKey_001] ON [dbo].[WorkingKey] (Terminal ASC)
	INCLUDE (ChaveTrabalho, Estabelecimento)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

