CREATE TABLE [dbo].[ChaveAberturaTEF] ( 
	[ChaveAberturaTefCodigo] INT IDENTITY(1,1) NOT NULL
	,[Estabelecimento] INT NOT NULL
	,[ChaveTrabalho] VARCHAR(16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[DataCriacaoChave] DATETIME NOT NULL
	,[Provedor] VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[IDX_DES] INT NULL
	,[IDX_3DES] INT NULL
	,CONSTRAINT [PK_ChaveAberturaTEF] PRIMARY KEY CLUSTERED (ChaveAberturaTefCodigo DESC) WITH FILLFACTOR = 90
	);

CREATE NONCLUSTERED INDEX [IX_ChaveAberturaTEF_Provedor] ON [dbo].[ChaveAberturaTEF] (Provedor ASC)
	INCLUDE (ChaveAberturaTefCodigo, ChaveTrabalho)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_ChaveAberturaTEF_Estabelecimento_Provedor] ON [dbo].[ChaveAberturaTEF] (Estabelecimento ASC, Provedor ASC)
	INCLUDE (ChaveTrabalho)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IDX_N_ChaveAberturaTEF_001] ON [dbo].[ChaveAberturaTEF] (Provedor ASC)
	INCLUDE (ChaveTrabalho, DataCriacaoChave)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

