CREATE TABLE [dbo].[NSUTransacoes] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[Data] DATETIME NULL
	);

CREATE CLUSTERED INDEX [IX_CODIGO] ON [dbo].[NSUTransacoes] (Codigo ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 100, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

