CREATE TABLE [dbo].[TelefonesSMS] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[Telefone] VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[DataCadastro] DATETIME NOT NULL
	,[CpfUsuario] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Ativo] BIT NULL CONSTRAINT [DF__Telefones__Ativo__1ED998B2] DEFAULT ((1))
	,CONSTRAINT [PK_TelefonesSMS] PRIMARY KEY CLUSTERED (Codigo ASC) WITH FILLFACTOR = 80
	);
