CREATE TABLE [dbo].[TiposTickets] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[Descricao] NVARCHAR(200) NULL
	,CONSTRAINT [PK_TiposTickets] PRIMARY KEY CLUSTERED (Codigo ASC) WITH FILLFACTOR = 80
	,CONSTRAINT [UQ__TiposTickets__3B75D760] UNIQUE NONCLUSTERED (Descricao ASC) WITH FILLFACTOR = 80
	);
