CREATE TABLE [dbo].[ControleSonda] ( 
	[Codigo] INT IDENTITY(1,1) NOT NULL
	,[NSU_Policard] INT NULL
	,[CodigoMensagem] CHAR(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Valor] DECIMAL(15,2) NULL
	,[NumeroCartao] CHAR(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[DataInicioSonda] DATETIME NULL
	,[DataRespSonda] DATETIME NULL
	,[BaseOrigem] CHAR(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[NsuOrigem] CHAR(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[StatusSonda] CHAR(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[Estabelecimento] VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[SondaEnviada] BIT NULL CONSTRAINT [DF__aut_Contr__Sonda__35FCF52C] DEFAULT ((0))
	,[NivelSonda] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[QtdSonda] TINYINT NULL
	,[DataGMT] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[DataLocal] VARCHAR(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[HoraLocal] VARCHAR(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,CONSTRAINT [PK_ControleSonda] PRIMARY KEY CLUSTERED (Codigo ASC) WITH FILLFACTOR = 80
	);

CREATE NONCLUSTERED INDEX [IDX_N_ControleSonda_001] ON [dbo].[ControleSonda] (DataRespSonda ASC, Estabelecimento ASC, DataInicioSonda ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 90, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IDX_N_ControleSonda_002] ON [dbo].[ControleSonda] (Estabelecimento ASC, DataInicioSonda ASC, StatusSonda ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 90, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IDX_N_ControleSonda_003] ON [dbo].[ControleSonda] (NSU_Policard ASC, Valor ASC, NumeroCartao ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 90, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

