CREATE TABLE [dbo].[LISTATELEFONE] ( 
	[ID] INT IDENTITY(1,1) NOT NULL
	,[TELEFONE] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[RESPONSAVEL] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	);
