CREATE TABLE [dbo].[EnviarPushApp] ( 
	[IdPush] BIGINT IDENTITY(1,1) NOT NULL
	,[TrnCodigo] BIGINT NULL
	,[BaseOrigem] CHAR(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[CntAPPCodigo] INT NULL
	,[Enviado] BIT NULL CONSTRAINT [DF__EnviarPus__Envia__0F4D3C5F] DEFAULT ((0))
	,[DataInsercao] DATETIME NULL
	,[CodigoResposta] INT NULL
	,[CodigoEstabelecimento] BIGINT NULL
	,[NumeroCartao] CHAR(16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[AuditCodigo] BIGINT NULL
	,CONSTRAINT [PK__EnviarPu__F9819F184E059225] PRIMARY KEY CLUSTERED (IdPush ASC) WITH FILLFACTOR = 100
	);

CREATE NONCLUSTERED INDEX [IX_EnviarPushApp_AuditCodigo] ON [dbo].[EnviarPushApp] (AuditCodigo ASC)
	WITH (PAD_INDEX = OFF, FILLFACTOR = 90, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF , ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY];

