CREATE TABLE [dbo].[aut_ChavesHSM_2] ( 
	[IdChave] INT IDENTITY(1,1) NOT NULL
	,[IdRede] INT NOT NULL
	,[Provedor] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[LabelChaveTDB] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[LabelChavePOS] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[LabelChaveRSA] VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	,[ChaveRSA] VARCHAR(2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[LenChaveRSA] INT NULL
	,[Data] DATETIME NULL
	,[Kcv] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[IdentificadorWK] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	,[LoteWK] VARCHAR(64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
	);
